import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { NextSeo } from 'next-seo'
import { dehydrate, QueryClient } from 'react-query'
import { GetLocationsQuery, useGetLocationsQuery } from 'src/generated'

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(
    useGetLocationsQuery.getKey(),
    useGetLocationsQuery.fetcher({ page: 20 })
  )

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  }
}

const About: NextPage = () => {
  const { isLoading, isError, data } = useGetLocationsQuery<GetLocationsQuery>()

  if (isLoading) return <div>Loading...</div>
  if (isError) return <div>Something went wrong.</div>

  return (
    <div>
      <NextSeo
        title='About - Next boilerplate.'
        description='A short description goes here which says what goes here.'
      />

      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{JSON.stringify(data, null, 2)}</main>

      <Link href='/'>Back to Home</Link>
    </div>
  )
}

export default About
