import { useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { NextSeo } from 'next-seo'
import { dehydrate, QueryClient } from 'react-query'
import { GetCharactersQuery, useGetCharactersQuery } from 'src/generated'

export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(
    useGetCharactersQuery.getKey(),
    useGetCharactersQuery.fetcher({ page: 20 })
  )

  return {
    props: {
      dehydratedState: JSON.parse(JSON.stringify(dehydrate(queryClient))),
    },
  }
}

const Home: NextPage = () => {
  const obj = { title: 'Hello World' }
  const [text, setText] = useState(JSON.stringify(obj))
  const { isLoading, isError, data } =
    useGetCharactersQuery<GetCharactersQuery>()

  if (isLoading) return <div>Loading...</div>
  if (isError) return <div>Something went wrong.</div>

  return (
    <div>
      {text}
      <NextSeo
        title='Next boilerplate.'
        description='A short description goes here which says what goes here.'
      />
      {/** @ts-ignore */}
      <button type='button' onClick={() => setText(obj)}>
        Break things
      </button>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>{JSON.stringify(data, null, 2)}</main>
      <Link href='/about'>About</Link>

      <footer>Hello Footer</footer>
    </div>
  )
}

export default Home
